// <auto-generated />
using M133_M151_Jubilaeum_der_Musikkapelle_Seetalhorn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M133_M151_Jubilaeum_der_Musikkapelle_Seetalhorn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220404111122_FirstAttemptForDatabase")]
    partial class FirstAttemptForDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("M133_M151_Jubilaeum_der_Musikkapelle_Seetalhorn.Models.Seetalhorn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Punkte")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seetalhorn");
                });
#pragma warning restore 612, 618
        }
    }
}
